### ISSUE TITLE
run_singularity.py doesn't use output_dir flag

### ISSUE THREAD

**Issue by mokca** [prehensilecode/alphafold_singularity#28] opened 2023-03-13 13:21 UTC
The run_singularity.py script has an --output_dir flag but doesn't appear to use it.  

The flags summary says
```
  --output_dir: Path to a directory that will store the results.
    (default: '/tmp')
```
However, output_dir is set to the contents of TMP or TMPDIR if defined, or a generated temporary directory in tmp.
```
if 'TMP' in os.environ:
    output_dir = os.environ['TMP']
elif 'TMPDIR' in os.environ:
    output_dir = os.environ['TMPDIR']
else:
    output_dir = tempfile.mkdtemp(dir='/tmp', prefix='alphafold-')
```
The contents of FLAGS.output_dir don't appear to be used at any stage.

**Comment by prehensilecode** [comment] 2023-03-13 14:29
The variable `tmp_dir` is set to the value of `output_dir`. Then, `tmp_dir` is used for the bind in line 237.

**Comment by prehensilecode** [comment] 2023-06-04 19:06
Duplicate of #31

**Closed as completed by prehensilecode** 2023-06-04 19:06 UTC
